/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/aether /home/minecraft/server/bukkit/aether -12 12 -1 23
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/aether /home/minecraft/server/bukkit/aether 24 24 35 35
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/aether /home/minecraft/server/bukkit/aether 36 -24 47 -13
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/aether /home/minecraft/server/bukkit/aether -36 48 -25 59
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/aether /home/minecraft/server/bukkit/aether 36 84 47 95
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/aether /home/minecraft/server/bukkit/aether -48 84 -37 95
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 0 48 7 55
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 0 -56 7 -49
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 0 56 7 63
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 0 64 7 71
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -104 8 -97 15
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 16 -48 23 -41
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -16 80 -9 87
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 24 24 31 31
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 24 -8 31 -1
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 32 -96 39 -89
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 40 16 47 23
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 40 24 47 31
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 48 16 55 23
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 48 24 55 31
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -48 -8 -41 -1
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -56 -56 -49 -49
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -56 -64 -49 -57
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -64 -56 -57 -49
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -64 -64 -57 -57
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -72 -32 -65 -25
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -72 -40 -65 -33
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 8 -88 15 -81
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -80 0 -73 7
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -80 -32 -73 -25
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -80 -40 -73 -33
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -80 40 -73 47
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -80 48 -73 55
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire 80 72 87 79
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -80 -8 -73 -1
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -88 0 -81 7
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -88 -104 -81 -97
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/empire /home/minecraft/server/bukkit/empire -88 -8 -81 -1
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 0 -68 15 -53
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 152 68 152 83
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 153 67 168 67
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 153 68 168 83
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 153 84 168 84
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 153 85 168 100
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 169 68 169 83
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 169 84 169 84
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 169 85 169 100
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -17 -18 -2 -18
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 17 -85 32 -70
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 170 68 185 83
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 170 84 185 84
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 170 85 185 100
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -102 -18 -87
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -103 -18 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -18 -18 -18
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -34 -18 -19
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -35 -18 -35
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -51 -18 -36
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -52 -18 -52
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -68 -18 -53
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -69 -18 -69
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -85 -18 -70
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -18 -86 -18 -86
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 33 -85 33 -70
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -34 -103 -19 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 34 -85 49 -70
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -35 -103 -35 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 50 -85 50 -70
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 50 -86 50 -86
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -51 -102 -36 -87
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -51 -103 -36 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom 51 -85 66 -70
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -52 -102 -52 -87
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -52 -103 -52 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -68 -102 -53 -87
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -68 -103 -53 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -68 -119 -53 -104
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -69 -102 -69 -87
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -69 -103 -69 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -69 -119 -69 -104
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -69 -86 -69 -86
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/kingdom /home/minecraft/server/bukkit/kingdom -85 -103 -70 -103
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/skyblock /home/minecraft/server/bukkit/skyblock -16 24 -9 31
/home/minecraft/server/chunk/copychunk /disk2/tmp/minecraft/server/worlds/save/skyblock /home/minecraft/server/bukkit/skyblock -32 24 -25 31
