<?php
$UMC_DATA_112 = array(
    'acacia_boat' => array(
        'stack' => 1,
        'id' => 447,
        'display_name' => 'Acacia Boat',
    ),
    'acacia_door' => array(
        'stack' => 64,
        'id' => 430,
        'display_name' => 'Acacia Door',
    ),
    'acacia_fence' => array(
        'stack' => 64,
        'id' => 192,
        'display_name' => 'Acacia Fence',
    ),
    'acacia_fence_gate' => array(
        'stack' => 64,
        'id' => 187,
        'display_name' => 'Acacia Fence Gate',
    ),
    'acacia_stairs' => array(
        'stack' => 64,
        'id' => 163,
        'display_name' => 'Acacia Wood Stairs',
    ),
    'activator_rail' => array(
        'stack' => 64,
        'id' => 157,
        'display_name' => 'Activator Rail',
    ),
    'air' => array(
        'stack' => 0,
        'id' => 0,
        'display_name' => 'Air',
    ),
    'anvil' => array(
        'stack' => 64,
        'id' => 145,
        'display_name' => 'Anvil',
        'variations' => array(
            '0' => 'Anvil',
            '1' => 'Slightly Damaged Anvil',
            '2' => 'Very Damaged Anvil',
            '3' => 'Anvil (North/South)',
            '4' => 'Anvil (East/West)',
            '5' => 'Anvil (South/North)',
            '6' => 'Anvil (West/East)',
            '7' => 'Slightly Damaged Anvil (North/South)',
            '8' => 'Slightly Damaged Anvil (East/West)',
            '9' => 'Slightly Damaged Anvil (West/East)',
            '10' => 'Slightly Damaged Anvil (South/North)',
            '11' => 'Very Damaged Anvil (North/South)',
            '12' => 'Very Damaged Anvil (East/West)',
            '13' => 'Very Damaged Anvil (West/East)',
            '14' => 'Very Damaged Anvil (South/North)',
        ),
    ),
    'apple' => array(
        'stack' => 64,
        'id' => 260,
        'display_name' => 'Apple',
    ),
    'armor_stand' => array(
        'stack' => 16,
        'id' => 416,
        'display_name' => 'Armor Stand',
    ),
    'arrow' => array(
        'stack' => 64,
        'id' => 262,
        'display_name' => 'Arrow',
    ),
    'baked_potato' => array(
        'stack' => 64,
        'id' => 393,
        'display_name' => 'Baked Potato',
    ),
    'banner' => array(
        'stack' => 16,
        'id' => 425,
        'display_name' => 'Banner',
    ),
    'barrier' => array(
        'stack' => 64,
        'id' => 166,
        'display_name' => 'Barrier',
    ),
    'beacon' => array(
        'stack' => 64,
        'id' => 138,
        'display_name' => 'Beacon',
    ),
    'bed' => array(
        'stack' => 1,
        'id' => 355,
        'display_name' => 'Bed',
    ),
    'bedrock' => array(
        'stack' => 64,
        'id' => 7,
        'display_name' => 'Bedrock',
    ),
    'beef' => array(
        'stack' => 64,
        'id' => 363,
        'display_name' => 'Raw Beef',
    ),
    'beetroot' => array(
        'stack' => 64,
        'id' => 434,
        'display_name' => 'Beetroot',
    ),
    'beetroot_seeds' => array(
        'stack' => 64,
        'id' => 435,
        'display_name' => 'Beetroot Seeds',
    ),
    'beetroot_soup' => array(
        'stack' => 1,
        'id' => 436,
        'display_name' => 'Beetroot Soup',
    ),
    'beetroots' => array(
        'stack' => 64,
        'id' => 207,
        'display_name' => 'Beetroot Seeds',
    ),
    'birch_boat' => array(
        'stack' => 1,
        'id' => 445,
        'display_name' => 'Birch Boat',
    ),
    'birch_door' => array(
        'stack' => 64,
        'id' => 428,
        'display_name' => 'Birch Door',
    ),
    'birch_fence' => array(
        'stack' => 64,
        'id' => 189,
        'display_name' => 'Birch Fence',
    ),
    'birch_fence_gate' => array(
        'stack' => 64,
        'id' => 184,
        'display_name' => 'Birch Fence Gate',
    ),
    'birch_stairs' => array(
        'stack' => 64,
        'id' => 135,
        'display_name' => 'Birch Wood Stairs',
    ),
    'black_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 250,
        'display_name' => 'Black Glazed Terracotta',
    ),
    'black_shulker_box' => array(
        'stack' => 1,
        'id' => 234,
        'display_name' => 'Black Shulker Box',
    ),
    'blaze_powder' => array(
        'stack' => 64,
        'id' => 377,
        'display_name' => 'Blaze Powder',
    ),
    'blaze_rod' => array(
        'stack' => 64,
        'id' => 369,
        'display_name' => 'Blaze Rod',
    ),
    'blue_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 246,
        'display_name' => 'Blue Glazed Terracotta',
    ),
    'blue_shulker_box' => array(
        'stack' => 1,
        'id' => 230,
        'display_name' => 'Blue Shulker Box',
    ),
    'boat' => array(
        'stack' => 1,
        'id' => 333,
        'display_name' => 'Boat',
    ),
    'bone' => array(
        'stack' => 64,
        'id' => 352,
        'display_name' => 'Bone',
    ),
    'bone_block' => array(
        'stack' => 64,
        'id' => 216,
        'display_name' => 'Bone Block',
    ),
    'book' => array(
        'stack' => 64,
        'id' => 340,
        'display_name' => 'Book',
    ),
    'bookshelf' => array(
        'stack' => 64,
        'id' => 47,
        'display_name' => 'Bookshelf',
    ),
    'bow' => array(
        'stack' => 1,
        'id' => 261,
        'display_name' => 'Bow',
    ),
    'bowl' => array(
        'stack' => 64,
        'id' => 281,
        'display_name' => 'Bowl',
    ),
    'bread' => array(
        'stack' => 64,
        'id' => 297,
        'display_name' => 'Bread',
    ),
    'brewing_stand' => array(
        'stack' => 64,
        'id' => 379,
        'display_name' => 'Brewing Stand',
    ),
    'brick' => array(
        'stack' => 64,
        'id' => 336,
        'display_name' => 'Brick',
    ),
    'brick_block' => array(
        'stack' => 64,
        'id' => 45,
        'display_name' => 'Bricks',
    ),
    'brick_stairs' => array(
        'stack' => 64,
        'id' => 108,
        'display_name' => 'Brick Stairs',
    ),
    'brown_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 247,
        'display_name' => 'Brown Glazed Terracotta',
    ),
    'brown_mushroom' => array(
        'stack' => 64,
        'id' => 39,
        'display_name' => 'Brown Mushroom',
    ),
    'brown_mushroom_block' => array(
        'stack' => 64,
        'id' => 99,
        'display_name' => 'Brown Mushroom (block)',
        'variations' => array(
            '0' => 'Pores on all sides',
            '1' => 'Cap texture on top, west and north',
            '2' => 'Cap texture on top and north',
            '3' => 'Cap texture on top, north and east',
            '4' => 'Cap texture on top and west',
            '5' => 'Cap texture on top',
            '6' => 'Cap texture on top and east',
            '7' => 'Cap texture on top, south and west',
            '8' => 'Cap texture on top and south',
            '9' => 'Cap texture on top, east and south',
            '10' => 'Stem texture on all four sides, pores on top and bottom',
            '14' => 'Cap texture on all six sides',
            '15' => 'Stem texture on all six sides',
        ),
    ),
    'brown_shulker_box' => array(
        'stack' => 1,
        'id' => 231,
        'display_name' => 'Brown Shulker Box',
    ),
    'bucket' => array(
        'stack' => 16,
        'id' => 325,
        'display_name' => 'Bucket',
    ),
    'cactus' => array(
        'stack' => 64,
        'id' => 81,
        'display_name' => 'Cactus',
    ),
    'cake' => array(
        'stack' => 1,
        'id' => 354,
        'display_name' => 'Cake',
    ),
    'carpet' => array(
        'stack' => 64,
        'id' => 171,
        'display_name' => 'Carpet',
        'variations' => array(
            '0' => 'White Carpet',
            '1' => 'Orange Carpet',
            '2' => 'Magenta Carpet',
            '3' => 'Light Blue Carpet',
            '4' => 'Yellow Carpet',
            '5' => 'Lime Carpet',
            '6' => 'Pink Carpet',
            '7' => 'Gray Carpet',
            '8' => 'Light Gray Carpet',
            '9' => 'Cyan Carpet',
            '10' => 'Purple Carpet',
            '11' => 'Blue Carpet',
            '12' => 'Brown Carpet',
            '13' => 'Green Carpet',
            '14' => 'Red Carpet',
            '15' => 'Black Carpet',
        ),
    ),
    'carrot' => array(
        'stack' => 64,
        'id' => 391,
        'display_name' => 'Carrot',
    ),
    'carrot_on_a_stick' => array(
        'stack' => 1,
        'id' => 398,
        'display_name' => 'Carrot on a Stick',
    ),
    'carrots' => array(
        'stack' => 64,
        'id' => 141,
        'display_name' => 'Carrot',
    ),
    'cauldron' => array(
        'stack' => 64,
        'id' => 380,
        'display_name' => 'Cauldron',
    ),
    'chain_command_block' => array(
        'stack' => 64,
        'id' => 211,
        'display_name' => 'Chain Command Block',
    ),
    'chainmail_boots' => array(
        'stack' => 1,
        'id' => 305,
        'display_name' => 'Chain Boots',
    ),
    'chainmail_chestplate' => array(
        'stack' => 1,
        'id' => 303,
        'display_name' => 'Chain Chestplate',
    ),
    'chainmail_helmet' => array(
        'stack' => 1,
        'id' => 302,
        'display_name' => 'Chain Helmet',
    ),
    'chainmail_leggings' => array(
        'stack' => 1,
        'id' => 304,
        'display_name' => 'Chain Leggings',
    ),
    'chest' => array(
        'stack' => 64,
        'id' => 54,
        'display_name' => 'Chest',
    ),
    'chest_minecart' => array(
        'stack' => 1,
        'id' => 342,
        'display_name' => 'Minecart with Chest',
    ),
    'chicken' => array(
        'stack' => 64,
        'id' => 365,
        'display_name' => 'Raw Chicken',
    ),
    'chorus_flower' => array(
        'stack' => 64,
        'id' => 200,
        'display_name' => 'Chorus Flower',
    ),
    'chorus_fruit' => array(
        'stack' => 64,
        'id' => 432,
        'display_name' => 'Chorus Fruit',
    ),
    'chorus_fruit_popped' => array(
        'stack' => 64,
        'id' => 433,
        'display_name' => 'Popped Chorus Fruit',
    ),
    'chorus_plant' => array(
        'stack' => 64,
        'id' => 199,
        'display_name' => 'Chorus Plant',
    ),
    'clay' => array(
        'stack' => 64,
        'id' => 82,
        'display_name' => 'Clay',
    ),
    'clay_ball' => array(
        'stack' => 64,
        'id' => 337,
        'display_name' => 'Clay',
    ),
    'clock' => array(
        'stack' => 64,
        'id' => 347,
        'display_name' => 'Clock',
    ),
    'coal' => array(
        'stack' => 64,
        'id' => 263,
        'display_name' => 'Coal',
        'variations' => array(
            '0' => 'Coal',
            '1' => 'Charcoal',
        ),
    ),
    'coal_block' => array(
        'stack' => 64,
        'id' => 173,
        'display_name' => 'Block of Coal',
    ),
    'coal_ore' => array(
        'stack' => 64,
        'id' => 16,
        'display_name' => 'Coal Ore',
    ),
    'cobblestone' => array(
        'stack' => 64,
        'id' => 4,
        'display_name' => 'Cobblestone',
    ),
    'cobblestone_wall' => array(
        'stack' => 64,
        'id' => 139,
        'display_name' => 'Cobblestone Wall',
        'variations' => array(
            '0' => 'Cobblestone Wall',
            '1' => 'Mossy Cobblestone Wall',
        ),
    ),
    'cocoa' => array(
        'stack' => 64,
        'id' => 127,
        'display_name' => 'Cocoa',
    ),
    'command_block' => array(
        'stack' => 64,
        'id' => 137,
        'display_name' => 'Command Block',
    ),
    'command_block_minecart' => array(
        'stack' => 1,
        'id' => 422,
        'display_name' => 'Minecart with Command Block',
    ),
    'comparator' => array(
        'stack' => 64,
        'id' => 404,
        'display_name' => 'Redstone Comparator',
    ),
    'compass' => array(
        'stack' => 64,
        'id' => 345,
        'display_name' => 'Compass',
    ),
    'concrete' => array(
        'stack' => 64,
        'id' => 251,
        'display_name' => 'Concrete',
    ),
    'concrete_powder' => array(
        'stack' => 64,
        'id' => 252,
        'display_name' => 'Concrete Powder',
    ),
    'cooked_beef' => array(
        'stack' => 64,
        'id' => 364,
        'display_name' => 'Steak',
    ),
    'cooked_chicken' => array(
        'stack' => 64,
        'id' => 366,
        'display_name' => 'Cooked Chicken',
    ),
    'cooked_fish' => array(
        'stack' => 64,
        'id' => 350,
        'display_name' => 'Cooked Fish',
        'variations' => array(
            '0' => 'Raw Fish',
            '1' => 'Raw Salmon',
            '2' => 'Clownfish',
            '3' => 'Pufferfish',
            '4' => 'Cooked Fish',
            '5' => 'Cooked Salmon',
        ),
    ),
    'cooked_mutton' => array(
        'stack' => 64,
        'id' => 424,
        'display_name' => 'Cooked Mutton',
    ),
    'cooked_porkchop' => array(
        'stack' => 64,
        'id' => 320,
        'display_name' => 'Cooked Porkchop',
    ),
    'cooked_rabbit' => array(
        'stack' => 64,
        'id' => 412,
        'display_name' => 'Cooked Rabbit',
    ),
    'cookie' => array(
        'stack' => 64,
        'id' => 357,
        'display_name' => 'Cookie',
    ),
    'crafting_table' => array(
        'stack' => 64,
        'id' => 58,
        'display_name' => 'Crafting Table',
    ),
    'cyan_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 244,
        'display_name' => 'Cyan Glazed Terracotta',
    ),
    'cyan_shulker_box' => array(
        'stack' => 1,
        'id' => 228,
        'display_name' => 'Cyan Shulker Box',
    ),
    'dark_oak_boat' => array(
        'stack' => 1,
        'id' => 448,
        'display_name' => 'Dark Oak Boat',
    ),
    'dark_oak_door' => array(
        'stack' => 64,
        'id' => 431,
        'display_name' => 'Dark Oak Door',
    ),
    'dark_oak_fence' => array(
        'stack' => 64,
        'id' => 191,
        'display_name' => 'Dark Oak Fence',
    ),
    'dark_oak_fence_gate' => array(
        'stack' => 64,
        'id' => 186,
        'display_name' => 'Dark Oak Fence Gate',
    ),
    'dark_oak_stairs' => array(
        'stack' => 64,
        'id' => 164,
        'display_name' => 'Dark Oak Wood Stairs',
    ),
    'daylight_detector' => array(
        'stack' => 64,
        'id' => 151,
        'display_name' => 'Daylight Sensor',
    ),
    'daylight_detector_inverted' => array(
        'stack' => 64,
        'id' => 178,
        'display_name' => 'Inverted Daylight Sensor',
    ),
    'deadbush' => array(
        'stack' => 64,
        'id' => 32,
        'display_name' => 'Dead Bush',
    ),
    'detector_rail' => array(
        'stack' => 64,
        'id' => 28,
        'display_name' => 'Detector Rail',
    ),
    'diamond' => array(
        'stack' => 64,
        'id' => 264,
        'display_name' => 'Diamond',
    ),
    'diamond_axe' => array(
        'stack' => 1,
        'id' => 279,
        'display_name' => 'Diamond Axe',
    ),
    'diamond_block' => array(
        'stack' => 64,
        'id' => 57,
        'display_name' => 'Block of Diamond',
    ),
    'diamond_boots' => array(
        'stack' => 1,
        'id' => 313,
        'display_name' => 'Diamond Boots',
    ),
    'diamond_chestplate' => array(
        'stack' => 1,
        'id' => 311,
        'display_name' => 'Diamond Chestplate',
    ),
    'diamond_helmet' => array(
        'stack' => 1,
        'id' => 310,
        'display_name' => 'Diamond Helmet',
    ),
    'diamond_hoe' => array(
        'stack' => 1,
        'id' => 293,
        'display_name' => 'Diamond Hoe',
    ),
    'diamond_horse_armor' => array(
        'stack' => 1,
        'id' => 419,
        'display_name' => 'Diamond Horse Armor',
    ),
    'diamond_leggings' => array(
        'stack' => 1,
        'id' => 312,
        'display_name' => 'Diamond Leggings',
    ),
    'diamond_ore' => array(
        'stack' => 64,
        'id' => 56,
        'display_name' => 'Diamond Ore',
    ),
    'diamond_pickaxe' => array(
        'stack' => 1,
        'id' => 278,
        'display_name' => 'Diamond Pickaxe',
    ),
    'diamond_shovel' => array(
        'stack' => 1,
        'id' => 277,
        'display_name' => 'Diamond Shovel',
    ),
    'diamond_sword' => array(
        'stack' => 1,
        'id' => 276,
        'display_name' => 'Diamond Sword',
    ),
    'dirt' => array(
        'stack' => 64,
        'id' => 3,
        'display_name' => 'Dirt',
        'variations' => array(
            '0' => 'Dirt',
            '1' => 'Coarse Dirt',
            '2' => 'Podzol',
        ),
    ),
    'dispenser' => array(
        'stack' => 64,
        'id' => 23,
        'display_name' => 'Dispenser',
    ),
    'double_plant' => array(
        'stack' => 64,
        'id' => 175,
        'display_name' => 'Large Flowers',
        'variations' => array(
            '0' => 'Sunflower',
            '1' => 'Lilac',
            '2' => 'Double Tallgrass',
            '3' => 'Large Fern',
            '4' => 'Rose Bush',
            '5' => 'Peony',
            '8' => 'Top Half of any Large Plant; low three bits 0x7 are derived from the block below.',
        ),
    ),
    'double_stone_slab' => array(
        'stack' => 64,
        'id' => 43,
        'display_name' => 'Double Stone Slab',
        'variations' => array(
            '0' => 'Double Stone Slab',
            '1' => 'Double Sandstone Slab',
            '2' => 'Double (Stone) Wooden Slab',
            '3' => 'Double Cobblestone Slab',
            '4' => 'Double Bricks Slab',
            '5' => 'Double Stone Brick Slab',
            '6' => 'Double Nether Brick Slab',
            '7' => 'Double Quartz Slab',
            '8' => 'Smooth Double Stone Slab',
            '9' => 'Smooth Double Sandstone Slab',
            '15' => 'Tile Double Quartz Slab (note the underside)',
        ),
    ),
    'double_stone_slab2' => array(
        'stack' => 64,
        'id' => 181,
        'display_name' => 'Double Red Sandstone Slab',
        'variations' => array(
            '0' => 'Double Red Sandstone Slab',
            '8' => 'Smooth Double Red Sandstone Slab',
        ),
    ),
    'double_wooden_slab' => array(
        'stack' => 64,
        'id' => 125,
        'display_name' => 'Double Wooden Slab',
        'variations' => array(
            '0' => 'Double Oak Wood Slab',
            '1' => 'Double Spruce Wood Slab',
            '2' => 'Double Birch Wood Slab',
            '3' => 'Double Jungle Wood Slab',
            '4' => 'Double Acacia Wood Slab',
            '5' => 'Double Dark Oak Wood Slab',
        ),
    ),
    'dragon_breath' => array(
        'stack' => 64,
        'id' => 437,
        'display_name' => 'Dragon\'s Breath',
    ),
    'dragon_egg' => array(
        'stack' => 64,
        'id' => 122,
        'display_name' => 'Dragon Egg',
    ),
    'dropper' => array(
        'stack' => 64,
        'id' => 158,
        'display_name' => 'Dropper',
    ),
    'dye' => array(
        'stack' => 64,
        'id' => 351,
        'display_name' => 'Dye',
        'variations' => array(
            '0' => 'Ink Sac',
            '1' => 'Rose Red',
            '2' => 'Cactus Green',
            '3' => 'Cocoa Beans',
            '4' => 'Lapis Lazuli',
            '5' => 'Purple Dye',
            '6' => 'Cyan Dye',
            '7' => 'Light Gray Dye',
            '8' => 'Gray Dye',
            '9' => 'Pink Dye',
            '10' => 'Lime Dye',
            '11' => 'Dandelion Yellow',
            '12' => 'Light Blue Dye',
            '13' => 'Magenta Dye',
            '14' => 'Orange Dye',
            '15' => 'Bone Meal',
        ),
    ),
    'egg' => array(
        'stack' => 16,
        'id' => 344,
        'display_name' => 'Egg',
    ),
    'elytra' => array(
        'stack' => 1,
        'id' => 443,
        'display_name' => 'Elytra',
    ),
    'emerald' => array(
        'stack' => 64,
        'id' => 388,
        'display_name' => 'Emerald',
    ),
    'emerald_block' => array(
        'stack' => 64,
        'id' => 133,
        'display_name' => 'Block of Emerald',
    ),
    'emerald_ore' => array(
        'stack' => 64,
        'id' => 129,
        'display_name' => 'Emerald Ore',
    ),
    'enchanted_book' => array(
        'stack' => 1,
        'id' => 403,
        'display_name' => 'Enchanted Book',
    ),
    'enchanting_table' => array(
        'stack' => 64,
        'id' => 116,
        'display_name' => 'Enchantment Table',
    ),
    'end_bricks' => array(
        'stack' => 64,
        'id' => 206,
        'display_name' => 'End Stone Bricks',
    ),
    'end_crystal' => array(
        'stack' => 64,
        'id' => 426,
        'display_name' => 'End Crystal',
    ),
    'end_gateway' => array(
        'stack' => 0,
        'id' => 209,
        'display_name' => 'End Gateway',
    ),
    'end_portal' => array(
        'stack' => 0,
        'id' => 119,
        'display_name' => 'End Portal',
    ),
    'end_portal_frame' => array(
        'stack' => 64,
        'id' => 120,
        'display_name' => 'End Portal Frame',
    ),
    'end_rod' => array(
        'stack' => 64,
        'id' => 198,
        'display_name' => 'End Rod',
        'variations' => array(
            '0' => 'Facing down',
            '1' => 'Facing up',
            '2' => 'Facing north',
            '3' => 'Facing south',
            '4' => 'Facing west',
            '5' => 'Facing east',
        ),
    ),
    'end_stone' => array(
        'stack' => 64,
        'id' => 121,
        'display_name' => 'End Stone',
    ),
    'ender_chest' => array(
        'stack' => 64,
        'id' => 130,
        'display_name' => 'Ender Chest',
    ),
    'ender_eye' => array(
        'stack' => 64,
        'id' => 381,
        'display_name' => 'Eye of Ender',
    ),
    'ender_pearl' => array(
        'stack' => 16,
        'id' => 368,
        'display_name' => 'Ender Pearl',
    ),
    'experience_bottle' => array(
        'stack' => 64,
        'id' => 384,
        'display_name' => 'Bottle o\' Enchanting',
    ),
    'farmland' => array(
        'stack' => 64,
        'id' => 60,
        'display_name' => 'Farmland',
    ),
    'feather' => array(
        'stack' => 64,
        'id' => 288,
        'display_name' => 'Feather',
    ),
    'fence' => array(
        'stack' => 64,
        'id' => 85,
        'display_name' => 'Oak Fence',
    ),
    'fence_gate' => array(
        'stack' => 64,
        'id' => 107,
        'display_name' => 'Fence Gate',
    ),
    'fermented_spider_eye' => array(
        'stack' => 64,
        'id' => 376,
        'display_name' => 'Fermented Spider Eye',
    ),
    'filled_map' => array(
        'stack' => 64,
        'id' => 358,
        'display_name' => 'Map',
    ),
    'fire' => array(
        'stack' => 0,
        'id' => 51,
        'display_name' => 'Fire',
    ),
    'fire_charge' => array(
        'stack' => 64,
        'id' => 385,
        'display_name' => 'Fire Charge',
    ),
    'firework_charge' => array(
        'stack' => 64,
        'id' => 402,
        'display_name' => 'Firework Star',
    ),
    'fireworks' => array(
        'stack' => 64,
        'id' => 401,
        'display_name' => 'Firework Rocket',
    ),
    'fish' => array(
        'stack' => 64,
        'id' => 349,
        'display_name' => 'Raw Fish',
        'variations' => array(
            '0' => 'Raw Fish',
            '1' => 'Raw Salmon',
            '2' => 'Clownfish',
            '3' => 'Pufferfish',
            '4' => 'Cooked Fish',
            '5' => 'Cooked Salmon',
        ),
    ),
    'fishing_rod' => array(
        'stack' => 1,
        'id' => 346,
        'display_name' => 'Fishing Rod',
    ),
    'flint' => array(
        'stack' => 64,
        'id' => 318,
        'display_name' => 'Flint',
    ),
    'flint_and_steel' => array(
        'stack' => 1,
        'id' => 259,
        'display_name' => 'Flint and Steel',
    ),
    'flower_pot' => array(
        'stack' => 64,
        'id' => 390,
        'display_name' => 'Flower Pot',
    ),
    'flowing_lava' => array(
        'stack' => 0,
        'id' => 10,
        'display_name' => 'Lava',
    ),
    'flowing_water' => array(
        'stack' => 0,
        'id' => 8,
        'display_name' => 'Water',
    ),
    'frosted_ice' => array(
        'stack' => 0,
        'id' => 212,
        'display_name' => 'Frosted Ice',
    ),
    'furnace' => array(
        'stack' => 64,
        'id' => 61,
        'display_name' => 'Furnace',
    ),
    'furnace_minecart' => array(
        'stack' => 1,
        'id' => 343,
        'display_name' => 'Minecart with Furnace',
    ),
    'ghast_tear' => array(
        'stack' => 64,
        'id' => 370,
        'display_name' => 'Ghast Tear',
    ),
    'glass' => array(
        'stack' => 64,
        'id' => 20,
        'display_name' => 'Glass',
        'variations' => array(
            '0' => 'White Stained Glass',
            '1' => 'Orange Stained Glass',
            '2' => 'Magenta Stained Glass',
            '3' => 'Light Blue Stained Glass',
            '4' => 'Yellow Stained Glass',
            '5' => 'Lime Stained Glass',
            '6' => 'Pink Stained Glass',
            '7' => 'Gray Stained Glass',
            '8' => 'Light Gray Stained Glass',
            '9' => 'Cyan Stained Glass',
            '10' => 'Purple Stained Glass',
            '11' => 'Blue Stained Glass',
            '12' => 'Brown Stained Glass',
            '13' => 'Green Stained Glass',
            '14' => 'Red Stained Glass',
            '15' => 'Black Stained Glass',
        ),
    ),
    'glass_bottle' => array(
        'stack' => 64,
        'id' => 374,
        'display_name' => 'Glass Bottle',
    ),
    'glass_pane' => array(
        'stack' => 64,
        'id' => 102,
        'display_name' => 'Glass Pane',
    ),
    'glowstone' => array(
        'stack' => 64,
        'id' => 89,
        'display_name' => 'Glowstone',
    ),
    'glowstone_dust' => array(
        'stack' => 64,
        'id' => 348,
        'display_name' => 'Glowstone Dust',
    ),
    'gold_block' => array(
        'stack' => 64,
        'id' => 41,
        'display_name' => 'Block of Gold',
    ),
    'gold_ingot' => array(
        'stack' => 64,
        'id' => 266,
        'display_name' => 'Gold Ingot',
    ),
    'gold_nugget' => array(
        'stack' => 64,
        'id' => 371,
        'display_name' => 'Gold Nugget',
    ),
    'gold_ore' => array(
        'stack' => 64,
        'id' => 14,
        'display_name' => 'Gold Ore',
    ),
    'golden_apple' => array(
        'stack' => 64,
        'id' => 322,
        'display_name' => 'Golden Apple',
        'variations' => array(
            '0' => 'Golden Apple',
            '1' => 'Enchanted Golden Apple',
        ),
    ),
    'golden_axe' => array(
        'stack' => 1,
        'id' => 286,
        'display_name' => 'Golden Axe',
    ),
    'golden_boots' => array(
        'stack' => 1,
        'id' => 317,
        'display_name' => 'Golden Boots',
    ),
    'golden_carrot' => array(
        'stack' => 64,
        'id' => 396,
        'display_name' => 'Golden Carrot',
    ),
    'golden_chestplate' => array(
        'stack' => 1,
        'id' => 315,
        'display_name' => 'Golden Chestplate',
    ),
    'golden_helmet' => array(
        'stack' => 1,
        'id' => 314,
        'display_name' => 'Golden Helmet',
    ),
    'golden_hoe' => array(
        'stack' => 1,
        'id' => 294,
        'display_name' => 'Golden Hoe',
    ),
    'golden_horse_armor' => array(
        'stack' => 1,
        'id' => 418,
        'display_name' => 'Golden Horse Armor',
    ),
    'golden_leggings' => array(
        'stack' => 1,
        'id' => 316,
        'display_name' => 'Golden Leggings',
    ),
    'golden_pickaxe' => array(
        'stack' => 1,
        'id' => 285,
        'display_name' => 'Golden Pickaxe',
    ),
    'golden_rail' => array(
        'stack' => 64,
        'id' => 27,
        'display_name' => 'Powered Rail',
    ),
    'golden_shovel' => array(
        'stack' => 1,
        'id' => 284,
        'display_name' => 'Golden Shovel',
    ),
    'golden_sword' => array(
        'stack' => 1,
        'id' => 283,
        'display_name' => 'Golden Sword',
    ),
    'grass' => array(
        'stack' => 64,
        'id' => 2,
        'display_name' => 'Grass Block',
    ),
    'grass_path' => array(
        'stack' => 64,
        'id' => 208,
        'display_name' => 'Grass Path',
    ),
    'gravel' => array(
        'stack' => 64,
        'id' => 13,
        'display_name' => 'Gravel',
    ),
    'gray_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 242,
        'display_name' => 'Gray Glazed Terracotta',
    ),
    'gray_shulker_box' => array(
        'stack' => 1,
        'id' => 226,
        'display_name' => 'Gray Shulker Box',
    ),
    'green_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 248,
        'display_name' => 'Green Glazed Terracotta',
    ),
    'green_shulker_box' => array(
        'stack' => 1,
        'id' => 232,
        'display_name' => 'Green Shulker Box',
    ),
    'gunpowder' => array(
        'stack' => 64,
        'id' => 289,
        'display_name' => 'Gunpowder',
    ),
    'hardened_clay' => array(
        'stack' => 64,
        'id' => 172,
        'display_name' => 'Hardened Clay',
        'variations' => array(
            '0' => 'White hardened clay',
            '1' => 'Orange hardened clay',
            '2' => 'Magenta hardened clay',
            '3' => 'Light blue hardened clay',
            '4' => 'Yellow hardened clay',
            '5' => 'Lime hardened clay',
            '6' => 'Pink hardened clay',
            '7' => 'Gray hardened clay',
            '8' => 'Light gray hardened clay',
            '9' => 'Cyan hardened clay',
            '10' => 'Purple hardened clay',
            '11' => 'Blue hardened clay',
            '12' => 'Brown hardened clay',
            '13' => 'Green hardened clay',
            '14' => 'Red hardened clay',
            '15' => 'Black hardened clay',
        ),
    ),
    'hay_block' => array(
        'stack' => 64,
        'id' => 170,
        'display_name' => 'Hay Bale',
    ),
    'heavy_weighted_pressure_plate' => array(
        'stack' => 64,
        'id' => 148,
        'display_name' => 'Weighted Pressure Plate (Heavy)',
    ),
    'hopper' => array(
        'stack' => 64,
        'id' => 154,
        'display_name' => 'Hopper',
    ),
    'hopper_minecart' => array(
        'stack' => 1,
        'id' => 408,
        'display_name' => 'Minecart with Hopper',
    ),
    'ice' => array(
        'stack' => 64,
        'id' => 79,
        'display_name' => 'Ice',
    ),
    'iron_axe' => array(
        'stack' => 1,
        'id' => 258,
        'display_name' => 'Iron Axe',
    ),
    'iron_bars' => array(
        'stack' => 64,
        'id' => 101,
        'display_name' => 'Iron Bars',
    ),
    'iron_block' => array(
        'stack' => 64,
        'id' => 42,
        'display_name' => 'Block of Iron',
    ),
    'iron_boots' => array(
        'stack' => 1,
        'id' => 309,
        'display_name' => 'Iron Boots',
    ),
    'iron_chestplate' => array(
        'stack' => 1,
        'id' => 307,
        'display_name' => 'Iron Chestplate',
    ),
    'iron_door' => array(
        'stack' => 64,
        'id' => 330,
        'display_name' => 'Iron Door',
    ),
    'iron_helmet' => array(
        'stack' => 1,
        'id' => 306,
        'display_name' => 'Iron Helmet',
    ),
    'iron_hoe' => array(
        'stack' => 1,
        'id' => 292,
        'display_name' => 'Iron Hoe',
    ),
    'iron_horse_armor' => array(
        'stack' => 1,
        'id' => 417,
        'display_name' => 'Iron Horse Armor',
    ),
    'iron_ingot' => array(
        'stack' => 64,
        'id' => 265,
        'display_name' => 'Iron Ingot',
    ),
    'iron_leggings' => array(
        'stack' => 1,
        'id' => 308,
        'display_name' => 'Iron Leggings',
    ),
    'iron_nugget' => array(
        'stack' => 64,
        'id' => 452,
        'display_name' => 'Iron Nugget',
    ),
    'iron_ore' => array(
        'stack' => 64,
        'id' => 15,
        'display_name' => 'Iron Ore',
    ),
    'iron_pickaxe' => array(
        'stack' => 1,
        'id' => 257,
        'display_name' => 'Iron Pickaxe',
    ),
    'iron_shovel' => array(
        'stack' => 1,
        'id' => 256,
        'display_name' => 'Iron Shovel',
    ),
    'iron_sword' => array(
        'stack' => 1,
        'id' => 267,
        'display_name' => 'Iron Sword',
    ),
    'iron_trapdoor' => array(
        'stack' => 64,
        'id' => 167,
        'display_name' => 'Iron Trapdoor',
    ),
    'item_frame' => array(
        'stack' => 64,
        'id' => 389,
        'display_name' => 'Item Frame',
    ),
    'jukebox' => array(
        'stack' => 64,
        'id' => 84,
        'display_name' => 'Jukebox',
        'variations' => array(
            '0' => 'No disc inserted',
            '1' => 'Contains a disc',
        ),
    ),
    'jungle_boat' => array(
        'stack' => 1,
        'id' => 446,
        'display_name' => 'Jungle Boat',
    ),
    'jungle_door' => array(
        'stack' => 64,
        'id' => 429,
        'display_name' => 'Jungle Door',
    ),
    'jungle_fence' => array(
        'stack' => 64,
        'id' => 190,
        'display_name' => 'Jungle Fence',
    ),
    'jungle_fence_gate' => array(
        'stack' => 64,
        'id' => 185,
        'display_name' => 'Jungle Fence Gate',
    ),
    'jungle_stairs' => array(
        'stack' => 64,
        'id' => 136,
        'display_name' => 'Jungle Wood Stairs',
    ),
    'ladder' => array(
        'stack' => 64,
        'id' => 65,
        'display_name' => 'Ladder',
    ),
    'lapis_block' => array(
        'stack' => 64,
        'id' => 22,
        'display_name' => 'Lapis Lazuli Block',
    ),
    'lapis_ore' => array(
        'stack' => 64,
        'id' => 21,
        'display_name' => 'Lapis Lazuli Ore',
    ),
    'lava' => array(
        'stack' => 0,
        'id' => 11,
        'display_name' => 'Stationary Lava',
    ),
    'lava_bucket' => array(
        'stack' => 1,
        'id' => 327,
        'display_name' => 'Lava Bucket',
    ),
    'lead' => array(
        'stack' => 64,
        'id' => 420,
        'display_name' => 'Lead',
    ),
    'leather' => array(
        'stack' => 64,
        'id' => 334,
        'display_name' => 'Leather',
    ),
    'leather_boots' => array(
        'stack' => 1,
        'id' => 301,
        'display_name' => 'Leather Boots',
    ),
    'leather_chestplate' => array(
        'stack' => 1,
        'id' => 299,
        'display_name' => 'Leather Tunic',
    ),
    'leather_helmet' => array(
        'stack' => 1,
        'id' => 298,
        'display_name' => 'Leather Cap',
    ),
    'leather_leggings' => array(
        'stack' => 1,
        'id' => 300,
        'display_name' => 'Leather Pants',
    ),
    'leaves' => array(
        'stack' => 64,
        'id' => 18,
        'display_name' => 'Leaves',
        'variations' => array(
            '0' => 'Oak Leaves',
            '1' => 'Spruce Leaves',
            '2' => 'Birch Leaves',
            '3' => 'Jungle Leaves',
            '4' => 'Oak Leaves (no decay)',
            '5' => 'Spruce Leaves (no decay)',
            '6' => 'Birch Leaves (no decay)',
            '7' => 'Jungle Leaves (no decay)',
            '8' => 'Oak Leaves (check decay)',
            '9' => 'Spruce Leaves (check decay)',
            '10' => 'Birch Leaves (check decay)',
            '11' => 'Jungle Leaves (check decay)',
            '12' => 'Oak Leaves (no decay and check decay)',
            '13' => 'Spruce Leaves (no decay and check decay)',
            '14' => 'Birch Leaves (no decay and check decay)',
            '15' => 'Jungle Leaves (no decay and check decay)',
        ),
    ),
    'leaves2' => array(
        'stack' => 64,
        'id' => 161,
        'display_name' => 'Leaves (Acacia/Dark Oak)',
        'variations' => array(
            '0' => 'Acacia Leaves',
            '1' => 'Dark Oak Leaves',
            '4' => 'Acacia Leaves (no decay)',
            '5' => 'Dark Oak Leaves (no decay)',
            '8' => 'Acacia Leaves (check decay)',
            '9' => 'Dark Oak Leaves (check decay)',
            '12' => 'Acacia Leaves (no decay and check decay)',
            '13' => 'Dark Oak Leaves (no decay and check decay)',
        ),
    ),
    'lever' => array(
        'stack' => 64,
        'id' => 69,
        'display_name' => 'Lever',
    ),
    'light_blue_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 238,
        'display_name' => 'Light Blue Glazed Terracotta',
    ),
    'light_blue_shulker_box' => array(
        'stack' => 1,
        'id' => 222,
        'display_name' => 'Light Blue Shulker Box',
    ),
    'light_gray_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 243,
        'display_name' => 'Light Gray Glazed Terracotta',
    ),
    'light_gray_shulker_box' => array(
        'stack' => 1,
        'id' => 227,
        'display_name' => 'Light Gray Shulker Box',
    ),
    'light_weighted_pressure_plate' => array(
        'stack' => 64,
        'id' => 147,
        'display_name' => 'Weighted Pressure Plate (Light)',
    ),
    'lime_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 240,
        'display_name' => 'Lime Glazed Terracotta',
    ),
    'lime_shulker_box' => array(
        'stack' => 1,
        'id' => 224,
        'display_name' => 'Lime Shulker Box',
    ),
    'lingering_potion' => array(
        'stack' => 1,
        'id' => 441,
        'display_name' => 'Lingering Potion',
    ),
    'lit_furnace' => array(
        'stack' => 64,
        'id' => 62,
        'display_name' => 'Burning Furnace',
    ),
    'lit_pumpkin' => array(
        'stack' => 64,
        'id' => 91,
        'display_name' => 'Jack o\'Lantern',
    ),
    'lit_redstone_lamp' => array(
        'stack' => 64,
        'id' => 124,
        'display_name' => 'Redstone Lamp (active)',
    ),
    'lit_redstone_ore' => array(
        'stack' => 64,
        'id' => 74,
        'display_name' => 'Glowing Redstone Ore',
    ),
    'log' => array(
        'stack' => 64,
        'id' => 17,
        'display_name' => 'Wood',
    ),
    'log2' => array(
        'stack' => 64,
        'id' => 162,
        'display_name' => 'Wood (Acacia/Dark Oak)',
    ),
    'magenta_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 237,
        'display_name' => 'Magenta Glazed Terracotta',
    ),
    'magenta_shulker_box' => array(
        'stack' => 1,
        'id' => 221,
        'display_name' => 'Magenta Shulker Box',
    ),
    'magma' => array(
        'stack' => 64,
        'id' => 213,
        'display_name' => 'Magma Block',
    ),
    'magma_cream' => array(
        'stack' => 64,
        'id' => 378,
        'display_name' => 'Magma Cream',
    ),
    'map' => array(
        'stack' => 64,
        'id' => 395,
        'display_name' => 'Empty Map',
    ),
    'melon' => array(
        'stack' => 64,
        'id' => 360,
        'display_name' => 'Melon',
    ),
    'melon_block' => array(
        'stack' => 64,
        'id' => 103,
        'display_name' => 'Melon',
    ),
    'melon_seeds' => array(
        'stack' => 64,
        'id' => 362,
        'display_name' => 'Melon Seeds',
    ),
    'melon_stem' => array(
        'stack' => 64,
        'id' => 105,
        'display_name' => 'Melon Stem',
    ),
    'milk_bucket' => array(
        'stack' => 1,
        'id' => 335,
        'display_name' => 'Milk',
    ),
    'minecart' => array(
        'stack' => 1,
        'id' => 328,
        'display_name' => 'Minecart',
    ),
    'mob_spawner' => array(
        'stack' => 64,
        'id' => 52,
        'display_name' => 'Monster Spawner',
    ),
    'monster_egg' => array(
        'stack' => 64,
        'id' => 97,
        'display_name' => 'Monster Egg',
        'variations' => array(
            '0' => 'Stone Monster Egg',
            '1' => 'Cobblestone Monster Egg',
            '2' => 'Stone Brick Monster Egg',
            '3' => 'Mossy Stone Brick Monster Egg',
            '4' => 'Cracked Stone Brick Monster Egg',
            '5' => 'Chiseled Stone Brick Monster Egg',
        ),
    ),
    'mossy_cobblestone' => array(
        'stack' => 64,
        'id' => 48,
        'display_name' => 'Moss Stone',
    ),
    'mushroom_stew' => array(
        'stack' => 1,
        'id' => 282,
        'display_name' => 'Mushroom Stew',
    ),
    'mutton' => array(
        'stack' => 64,
        'id' => 423,
        'display_name' => 'Raw Mutton',
    ),
    'mycelium' => array(
        'stack' => 64,
        'id' => 110,
        'display_name' => 'Mycelium',
    ),
    'name_tag' => array(
        'stack' => 64,
        'id' => 421,
        'display_name' => 'Name Tag',
    ),
    'nether_brick' => array(
        'stack' => 64,
        'id' => 112,
        'display_name' => 'Nether Brick',
    ),
    'nether_brick_fence' => array(
        'stack' => 64,
        'id' => 113,
        'display_name' => 'Nether Brick Fence',
    ),
    'nether_brick_stairs' => array(
        'stack' => 64,
        'id' => 114,
        'display_name' => 'Nether Brick Stairs',
    ),
    'nether_star' => array(
        'stack' => 64,
        'id' => 399,
        'display_name' => 'Nether Star',
    ),
    'nether_wart' => array(
        'stack' => 64,
        'id' => 372,
        'display_name' => 'Nether Wart',
    ),
    'nether_wart_block' => array(
        'stack' => 64,
        'id' => 214,
        'display_name' => 'Nether Wart Block',
    ),
    'netherbrick' => array(
        'stack' => 64,
        'id' => 405,
        'display_name' => 'Nether Brick',
    ),
    'netherrack' => array(
        'stack' => 64,
        'id' => 87,
        'display_name' => 'Netherrack',
    ),
    'noteblock' => array(
        'stack' => 64,
        'id' => 25,
        'display_name' => 'Note Block',
    ),
    'oak_stairs' => array(
        'stack' => 64,
        'id' => 53,
        'display_name' => 'Oak Wood Stairs',
    ),
    'observer' => array(
        'stack' => 64,
        'id' => 218,
        'display_name' => 'Observer',
    ),
    'obsidian' => array(
        'stack' => 64,
        'id' => 49,
        'display_name' => 'Obsidian',
    ),
    'orange_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 236,
        'display_name' => 'Orange Glazed Terracotta',
    ),
    'orange_shulker_box' => array(
        'stack' => 1,
        'id' => 220,
        'display_name' => 'Orange Shulker Box',
    ),
    'packed_ice' => array(
        'stack' => 64,
        'id' => 174,
        'display_name' => 'Packed Ice',
    ),
    'painting' => array(
        'stack' => 64,
        'id' => 321,
        'display_name' => 'Painting',
    ),
    'paper' => array(
        'stack' => 64,
        'id' => 339,
        'display_name' => 'Paper',
    ),
    'pink_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 241,
        'display_name' => 'Pink Glazed Terracotta',
    ),
    'pink_shulker_box' => array(
        'stack' => 1,
        'id' => 225,
        'display_name' => 'Pink Shulker Box',
    ),
    'piston' => array(
        'stack' => 64,
        'id' => 33,
        'display_name' => 'Piston',
    ),
    'piston_extension' => array(
        'stack' => 64,
        'id' => 36,
        'display_name' => 'Block moved by Piston',
    ),
    'piston_head' => array(
        'stack' => 64,
        'id' => 34,
        'display_name' => 'Piston Head',
    ),
    'planks' => array(
        'stack' => 64,
        'id' => 5,
        'display_name' => 'Wood Planks',
        'variations' => array(
            '0' => 'Oak Wood Planks',
            '1' => 'Spruce Wood Planks',
            '2' => 'Birch Wood Planks',
            '3' => 'Jungle Wood Planks',
            '4' => 'Acacia Wood Planks',
            '5' => 'Dark Oak Wood Planks',
        ),
    ),
    'poisonous_potato' => array(
        'stack' => 64,
        'id' => 394,
        'display_name' => 'Poisonous Potato',
    ),
    'porkchop' => array(
        'stack' => 64,
        'id' => 319,
        'display_name' => 'Raw Porkchop',
    ),
    'portal' => array(
        'stack' => 0,
        'id' => 90,
        'display_name' => 'Nether Portal',
    ),
    'potato' => array(
        'stack' => 64,
        'id' => 392,
        'display_name' => 'Potato',
    ),
    'potatoes' => array(
        'stack' => 64,
        'id' => 142,
        'display_name' => 'Potato',
    ),
    'potion' => array(
        'stack' => 1,
        'id' => 373,
        'display_name' => 'Potion',
    ),
    'powered_comparator' => array(
        'stack' => 64,
        'id' => 150,
        'display_name' => 'Redstone Comparator (deprecated)',
    ),
    'powered_repeater' => array(
        'stack' => 64,
        'id' => 94,
        'display_name' => 'Redstone Repeater (active)',
    ),
    'prismarine' => array(
        'stack' => 64,
        'id' => 168,
        'display_name' => 'Prismarine',
        'variations' => array(
            '0' => 'Prismarine',
            '1' => 'Prismarine Bricks',
            '2' => 'Dark Prismarine',
        ),
    ),
    'prismarine_crystals' => array(
        'stack' => 64,
        'id' => 410,
        'display_name' => 'Prismarine Crystals',
    ),
    'prismarine_shard' => array(
        'stack' => 64,
        'id' => 409,
        'display_name' => 'Prismarine Shard',
    ),
    'pumpkin' => array(
        'stack' => 64,
        'id' => 86,
        'display_name' => 'Pumpkin',
    ),
    'pumpkin_pie' => array(
        'stack' => 64,
        'id' => 400,
        'display_name' => 'Pumpkin Pie',
    ),
    'pumpkin_seeds' => array(
        'stack' => 64,
        'id' => 361,
        'display_name' => 'Pumpkin Seeds',
    ),
    'pumpkin_stem' => array(
        'stack' => 64,
        'id' => 104,
        'display_name' => 'Pumpkin Stem',
    ),
    'purple_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 245,
        'display_name' => 'Purple Glazed Terracotta',
    ),
    'purple_shulker_box' => array(
        'stack' => 1,
        'id' => 229,
        'display_name' => 'Purple Shulker Box',
    ),
    'purpur_block' => array(
        'stack' => 64,
        'id' => 201,
        'display_name' => 'Purpur Block',
    ),
    'purpur_double_slab' => array(
        'stack' => 64,
        'id' => 204,
        'display_name' => 'Purpur Double Slab',
    ),
    'purpur_pillar' => array(
        'stack' => 64,
        'id' => 202,
        'display_name' => 'Purpur Pillar',
    ),
    'purpur_slab' => array(
        'stack' => 64,
        'id' => 205,
        'display_name' => 'Purpur Slab',
    ),
    'purpur_stairs' => array(
        'stack' => 64,
        'id' => 203,
        'display_name' => 'Purpur Stairs',
    ),
    'quartz' => array(
        'stack' => 64,
        'id' => 406,
        'display_name' => 'Nether Quartz',
    ),
    'quartz_block' => array(
        'stack' => 64,
        'id' => 155,
        'display_name' => 'Block of Quartz',
        'variations' => array(
            '0' => 'Block of Quartz',
            '1' => 'Chiseled Quartz Block',
            '2' => 'Pillar Quartz Block (vertical)',
            '3' => 'Pillar Quartz Block (north-south)',
            '4' => 'Pillar Quartz Block (east-west)',
        ),
    ),
    'quartz_ore' => array(
        'stack' => 64,
        'id' => 153,
        'display_name' => 'Nether Quartz Ore',
    ),
    'quartz_stairs' => array(
        'stack' => 64,
        'id' => 156,
        'display_name' => 'Quartz Stairs',
    ),
    'rabbit' => array(
        'stack' => 64,
        'id' => 411,
        'display_name' => 'Raw Rabbit',
    ),
    'rabbit_foot' => array(
        'stack' => 64,
        'id' => 414,
        'display_name' => 'Rabbit\'s Foot',
    ),
    'rabbit_hide' => array(
        'stack' => 64,
        'id' => 415,
        'display_name' => 'Rabbit Hide',
    ),
    'rabbit_stew' => array(
        'stack' => 1,
        'id' => 413,
        'display_name' => 'Rabbit Stew',
    ),
    'rail' => array(
        'stack' => 64,
        'id' => 66,
        'display_name' => 'Rail',
    ),
    'record_11' => array(
        'stack' => 1,
        'id' => 2266,
        'display_name' => '11 Disc',
    ),
    'record_13' => array(
        'stack' => 1,
        'id' => 2256,
        'display_name' => '13 Disc',
    ),
    'record_blocks' => array(
        'stack' => 1,
        'id' => 2258,
        'display_name' => 'Blocks Disc',
    ),
    'record_cat' => array(
        'stack' => 1,
        'id' => 2257,
        'display_name' => 'Cat Disc',
    ),
    'record_chirp' => array(
        'stack' => 1,
        'id' => 2259,
        'display_name' => 'Chirp Disc',
    ),
    'record_far' => array(
        'stack' => 1,
        'id' => 2260,
        'display_name' => 'Far Disc',
    ),
    'record_mall' => array(
        'stack' => 1,
        'id' => 2261,
        'display_name' => 'Mall Disc',
    ),
    'record_mellohi' => array(
        'stack' => 1,
        'id' => 2262,
        'display_name' => 'Mellohi Disc',
    ),
    'record_stal' => array(
        'stack' => 1,
        'id' => 2263,
        'display_name' => 'Stal Disc',
    ),
    'record_strad' => array(
        'stack' => 1,
        'id' => 2264,
        'display_name' => 'Strad Disc',
    ),
    'record_wait' => array(
        'stack' => 1,
        'id' => 2267,
        'display_name' => 'Wait Disc',
    ),
    'record_ward' => array(
        'stack' => 1,
        'id' => 2265,
        'display_name' => 'Ward Disc',
    ),
    'red_flower' => array(
        'stack' => 64,
        'id' => 38,
        'display_name' => 'Poppy',
        'variations' => array(
            '0' => 'Poppy',
            '1' => 'Blue Orchid',
            '2' => 'Allium',
            '3' => 'Azure Bluet',
            '4' => 'Red Tulip',
            '5' => 'Orange Tulip',
            '6' => 'White Tulip',
            '7' => 'Pink Tulip',
            '8' => 'Oxeye Daisy',
        ),
    ),
    'red_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 249,
        'display_name' => 'Red Glazed Terracotta',
    ),
    'red_mushroom' => array(
        'stack' => 64,
        'id' => 40,
        'display_name' => 'Red Mushroom',
    ),
    'red_mushroom_block' => array(
        'stack' => 64,
        'id' => 100,
        'display_name' => 'Red Mushroom (block)',
        'variations' => array(
            '0' => 'Pores on all sides',
            '1' => 'Cap texture on top, west and north',
            '2' => 'Cap texture on top and north',
            '3' => 'Cap texture on top, north and east',
            '4' => 'Cap texture on top and west',
            '5' => 'Cap texture on top',
            '6' => 'Cap texture on top and east',
            '7' => 'Cap texture on top, south and west',
            '8' => 'Cap texture on top and south',
            '9' => 'Cap texture on top, east and south',
            '10' => 'Stem texture on all four sides, pores on top and bottom',
            '14' => 'Cap texture on all six sides',
            '15' => 'Stem texture on all six sides',
        ),
    ),
    'red_nether_brick' => array(
        'stack' => 64,
        'id' => 215,
        'display_name' => 'Red Nether Brick',
    ),
    'red_sandstone' => array(
        'stack' => 64,
        'id' => 179,
        'display_name' => 'Red Sandstone',
        'variations' => array(
            '0' => 'Red Sandstone',
            '1' => 'Chiseled Red Sandstone',
            '2' => 'Smooth Red Sandstone',
        ),
    ),
    'red_sandstone_stairs' => array(
        'stack' => 64,
        'id' => 180,
        'display_name' => 'Red Sandstone Stairs',
    ),
    'red_shulker_box' => array(
        'stack' => 1,
        'id' => 233,
        'display_name' => 'Red Shulker Box',
    ),
    'redstone' => array(
        'stack' => 64,
        'id' => 331,
        'display_name' => 'Redstone',
    ),
    'redstone_block' => array(
        'stack' => 64,
        'id' => 152,
        'display_name' => 'Block of Redstone',
    ),
    'redstone_lamp' => array(
        'stack' => 64,
        'id' => 123,
        'display_name' => 'Redstone Lamp (inactive)',
    ),
    'redstone_ore' => array(
        'stack' => 64,
        'id' => 73,
        'display_name' => 'Redstone Ore',
    ),
    'redstone_torch' => array(
        'stack' => 64,
        'id' => 76,
        'display_name' => 'Redstone Torch (active)',
        'variations' => array(
            '0' => 'Facing east (attached to a block to its west)',
            '1' => 'Facing west (attached to a block to its east)',
            '2' => 'Facing south (attached to a block to its north)',
            '3' => 'Facing north (attached to a block to its south)',
            '4' => 'Facing up (attached to a block beneath it)',
        ),
    ),
    'redstone_wire' => array(
        'stack' => 64,
        'id' => 55,
        'display_name' => 'Redstone Wire',
    ),
    'reeds' => array(
        'stack' => 64,
        'id' => 338,
        'display_name' => 'Sugar Cane',
    ),
    'repeater' => array(
        'stack' => 64,
        'id' => 356,
        'display_name' => 'Redstone Repeater',
    ),
    'repeating_command_block' => array(
        'stack' => 64,
        'id' => 210,
        'display_name' => 'Repeating Command Block',
    ),
    'rotten_flesh' => array(
        'stack' => 64,
        'id' => 367,
        'display_name' => 'Rotten Flesh',
    ),
    'saddle' => array(
        'stack' => 1,
        'id' => 329,
        'display_name' => 'Saddle',
    ),
    'sand' => array(
        'stack' => 0,
        'id' => 12,
        'display_name' => 'Sand',
        'variations' => array(
            '0' => 'Sand',
            '1' => 'Red sand',
        ),
    ),
    'sandstone' => array(
        'stack' => 64,
        'id' => 24,
        'display_name' => 'Sandstone',
        'variations' => array(
            '0' => 'Sandstone',
            '1' => 'Chiseled sandstone',
            '2' => 'Smooth sandstone',
        ),
    ),
    'sandstone_stairs' => array(
        'stack' => 64,
        'id' => 128,
        'display_name' => 'Sandstone Stairs',
    ),
    'sapling' => array(
        'stack' => 64,
        'id' => 6,
        'display_name' => 'Sapling',
    ),
    'sea_lantern' => array(
        'stack' => 64,
        'id' => 169,
        'display_name' => 'Sea Lantern',
    ),
    'shears' => array(
        'stack' => 1,
        'id' => 359,
        'display_name' => 'Shears',
    ),
    'shield' => array(
        'stack' => 1,
        'id' => 442,
        'display_name' => 'Shield',
    ),
    'shulker_shell' => array(
        'stack' => 64,
        'id' => 450,
        'display_name' => 'Shulker Shell',
    ),
    'sign' => array(
        'stack' => 16,
        'id' => 323,
        'display_name' => 'Sign',
    ),
    'skull' => array(
        'stack' => 64,
        'id' => 397,
        'display_name' => 'Mob head',
        'variations' => array(
            '0' => 'Skeleton Skull',
            '1' => 'Wither Skeleton Skull',
            '2' => 'Zombie Head',
            '3' => 'Head',
            '4' => 'Creeper Head',
        ),
    ),
    'slime' => array(
        'stack' => 64,
        'id' => 165,
        'display_name' => 'Slime Block',
    ),
    'slime_ball' => array(
        'stack' => 64,
        'id' => 341,
        'display_name' => 'Slimeball',
    ),
    'snow' => array(
        'stack' => 64,
        'id' => 80,
        'display_name' => 'Snow',
    ),
    'snow_layer' => array(
        'stack' => 64,
        'id' => 78,
        'display_name' => 'Snow (layer)',
    ),
    'snowball' => array(
        'stack' => 16,
        'id' => 332,
        'display_name' => 'Snowball',
    ),
    'soul_sand' => array(
        'stack' => 64,
        'id' => 88,
        'display_name' => 'Soul Sand',
    ),
    'spawn_egg' => array(
        'stack' => 64,
        'id' => 383,
        'display_name' => 'Spawn Egg',
    ),
    'speckled_melon' => array(
        'stack' => 64,
        'id' => 382,
        'display_name' => 'Glistering Melon',
    ),
    'spectral_arrow' => array(
        'stack' => 64,
        'id' => 439,
        'display_name' => 'Spectral Arrow',
    ),
    'spider_eye' => array(
        'stack' => 64,
        'id' => 375,
        'display_name' => 'Spider Eye',
    ),
    'splash_potion' => array(
        'stack' => 1,
        'id' => 438,
        'display_name' => 'Splash Potion',
    ),
    'sponge' => array(
        'stack' => 64,
        'id' => 19,
        'display_name' => 'Sponge',
        'variations' => array(
            '0' => 'Sponge',
            '1' => 'Wet Sponge',
        ),
    ),
    'spruce_boat' => array(
        'stack' => 1,
        'id' => 444,
        'display_name' => 'Spruce Boat',
    ),
    'spruce_door' => array(
        'stack' => 64,
        'id' => 427,
        'display_name' => 'Spruce Door',
    ),
    'spruce_fence' => array(
        'stack' => 64,
        'id' => 188,
        'display_name' => 'Spruce Fence',
    ),
    'spruce_fence_gate' => array(
        'stack' => 64,
        'id' => 183,
        'display_name' => 'Spruce Fence Gate',
    ),
    'spruce_stairs' => array(
        'stack' => 64,
        'id' => 134,
        'display_name' => 'Spruce Wood Stairs',
    ),
    'stained_glass' => array(
        'stack' => 64,
        'id' => 95,
        'display_name' => 'Stained Glass',
        'variations' => array(
            '0' => 'White Stained Glass',
            '1' => 'Orange Stained Glass',
            '2' => 'Magenta Stained Glass',
            '3' => 'Light Blue Stained Glass',
            '4' => 'Yellow Stained Glass',
            '5' => 'Lime Stained Glass',
            '6' => 'Pink Stained Glass',
            '7' => 'Gray Stained Glass',
            '8' => 'Light Gray Stained Glass',
            '9' => 'Cyan Stained Glass',
            '10' => 'Purple Stained Glass',
            '11' => 'Blue Stained Glass',
            '12' => 'Brown Stained Glass',
            '13' => 'Green Stained Glass',
            '14' => 'Red Stained Glass',
            '15' => 'Black Stained Glass',
        ),
    ),
    'stained_glass_pane' => array(
        'stack' => 64,
        'id' => 160,
        'display_name' => 'Stained Glass Pane',
        'variations' => array(
            '0' => 'White Stained Glass Pane',
            '1' => 'Orange Stained Glass Pane',
            '2' => 'Magenta Stained Glass Pane',
            '3' => 'Light Blue Stained Glass Pane',
            '4' => 'Yellow Stained Glass Pane',
            '5' => 'Lime Stained Glass Pane',
            '6' => 'Pink Stained Glass Pane',
            '7' => 'Gray Stained Glass Pane',
            '8' => 'Light Gray Stained Glass Pane',
            '9' => 'Cyan Stained Glass Pane',
            '10' => 'Purple Stained Glass Pane',
            '11' => 'Blue Stained Glass Pane',
            '12' => 'Brown Stained Glass Pane',
            '13' => 'Green Stained Glass Pane',
            '14' => 'Red Stained Glass Pane',
            '15' => 'Black Stained Glass Pane',
        ),
    ),
    'stained_hardened_clay' => array(
        'stack' => 64,
        'id' => 159,
        'display_name' => 'Stained Clay',
        'variations' => array(
            '0' => 'White hardened clay',
            '1' => 'Orange hardened clay',
            '2' => 'Magenta hardened clay',
            '3' => 'Light blue hardened clay',
            '4' => 'Yellow hardened clay',
            '5' => 'Lime hardened clay',
            '6' => 'Pink hardened clay',
            '7' => 'Gray hardened clay',
            '8' => 'Light gray hardened clay',
            '9' => 'Cyan hardened clay',
            '10' => 'Purple hardened clay',
            '11' => 'Blue hardened clay',
            '12' => 'Brown hardened clay',
            '13' => 'Green hardened clay',
            '14' => 'Red hardened clay',
            '15' => 'Black hardened clay',
        ),
    ),
    'standing_banner' => array(
        'stack' => 16,
        'id' => 176,
        'display_name' => 'Standing Banner',
    ),
    'standing_sign' => array(
        'stack' => 16,
        'id' => 63,
        'display_name' => 'Standing Sign',
    ),
    'stick' => array(
        'stack' => 64,
        'id' => 280,
        'display_name' => 'Stick',
    ),
    'sticky_piston' => array(
        'stack' => 64,
        'id' => 29,
        'display_name' => 'Sticky Piston',
    ),
    'stone' => array(
        'stack' => 64,
        'id' => 1,
        'display_name' => 'Stone',
    ),
    'stone_axe' => array(
        'stack' => 1,
        'id' => 275,
        'display_name' => 'Stone Axe',
    ),
    'stone_brick_stairs' => array(
        'stack' => 64,
        'id' => 109,
        'display_name' => 'Stone Brick Stairs',
    ),
    'stone_button' => array(
        'stack' => 64,
        'id' => 77,
        'display_name' => 'Stone Button',
    ),
    'stone_hoe' => array(
        'stack' => 1,
        'id' => 291,
        'display_name' => 'Stone Hoe',
    ),
    'stone_pickaxe' => array(
        'stack' => 1,
        'id' => 274,
        'display_name' => 'Stone Pickaxe',
    ),
    'stone_pressure_plate' => array(
        'stack' => 64,
        'id' => 70,
        'display_name' => 'Stone Pressure Plate',
    ),
    'stone_shovel' => array(
        'stack' => 1,
        'id' => 273,
        'display_name' => 'Stone Shovel',
    ),
    'stone_slab' => array(
        'stack' => 64,
        'id' => 44,
        'display_name' => 'Stone Slab',
        'variations' => array(
            '0' => 'Stone Slab',
            '1' => 'Sandstone Slab',
            '2' => '(Stone) Wooden Slab',
            '3' => 'Cobblestone Slab',
            '4' => 'Bricks Slab',
            '5' => 'Stone Brick Slab',
            '6' => 'Nether Brick Slab',
            '7' => 'Quartz Slab',
            '8' => 'Upper Stone Slab',
            '9' => 'Upper Sandstone Slab',
            '10' => 'Upper (Stone) Wooden Slab',
            '11' => 'Upper Cobblestone Slab',
            '12' => 'Upper Bricks Slab',
            '13' => 'Upper Stone Brick Slab',
            '14' => 'Upper Nether Brick Slab',
            '15' => 'Upper Quartz Slab',
        ),
    ),
    'stone_slab2' => array(
        'stack' => 64,
        'id' => 182,
        'display_name' => 'Red Sandstone Slab',
        'variations' => array(
            '0' => 'Red Sandstone Slab',
            '8' => 'Upper Red Sandstone Slab',
        ),
    ),
    'stone_stairs' => array(
        'stack' => 64,
        'id' => 67,
        'display_name' => 'Cobblestone Stairs',
    ),
    'stone_sword' => array(
        'stack' => 1,
        'id' => 272,
        'display_name' => 'Stone Sword',
    ),
    'stonebrick' => array(
        'stack' => 64,
        'id' => 98,
        'display_name' => 'Stone Bricks',
        'variations' => array(
            '0' => 'Stone brick',
            '1' => 'Mossy stone brick',
            '2' => 'Cracked stone brick',
            '3' => 'Chiseled stone brick',
        ),
    ),
    'string' => array(
        'stack' => 64,
        'id' => 287,
        'display_name' => 'String',
    ),
    'structure_block' => array(
        'stack' => 64,
        'id' => 255,
        'display_name' => 'Structure Block',
        'variations' => array(
            '0' => 'Save',
            '1' => 'Load',
            '2' => 'Corner',
            '3' => 'Data',
        ),
    ),
    'structure_void' => array(
        'stack' => 64,
        'id' => 217,
        'display_name' => 'Structure Void',
        'variations' => array(
            '0' => 'Save',
            '1' => 'Load',
            '2' => 'Corner',
            '3' => 'Data',
        ),
    ),
    'sugar' => array(
        'stack' => 64,
        'id' => 353,
        'display_name' => 'Sugar',
    ),
    'tallgrass' => array(
        'stack' => 64,
        'id' => 31,
        'display_name' => 'Grass',
        'variations' => array(
            '0' => 'Shrub',
            '1' => 'Tall Grass',
            '2' => 'Fern',
        ),
    ),
    'tipped_arrow' => array(
        'stack' => 64,
        'id' => 440,
        'display_name' => 'Tipped Arrow',
    ),
    'tnt' => array(
        'stack' => 64,
        'id' => 46,
        'display_name' => 'TNT',
        'variations' => array(
            '0' => 'Drops a TNT item when broken',
            '1' => 'Activates when broken',
        ),
    ),
    'tnt_minecart' => array(
        'stack' => 1,
        'id' => 407,
        'display_name' => 'Minecart with TNT',
    ),
    'torch' => array(
        'stack' => 64,
        'id' => 50,
        'display_name' => 'Torch',
        'variations' => array(
            '0' => 'Facing east (attached to a block to its west)',
            '1' => 'Facing west (attached to a block to its east)',
            '2' => 'Facing south (attached to a block to its north)',
            '3' => 'Facing north (attached to a block to its south)',
            '4' => 'Facing up (attached to a block beneath it)',
        ),
    ),
    'totem_of_undying' => array(
        'stack' => 1,
        'id' => 449,
        'display_name' => 'Totem of Undying',
    ),
    'trapdoor' => array(
        'stack' => 64,
        'id' => 96,
        'display_name' => 'Trapdoor',
    ),
    'trapped_chest' => array(
        'stack' => 64,
        'id' => 146,
        'display_name' => 'Trapped Chest',
    ),
    'tripwire' => array(
        'stack' => 64,
        'id' => 132,
        'display_name' => 'Tripwire',
    ),
    'tripwire_hook' => array(
        'stack' => 64,
        'id' => 131,
        'display_name' => 'Tripwire Hook',
    ),
    'unlit_redstone_torch' => array(
        'stack' => 64,
        'id' => 75,
        'display_name' => 'Redstone Torch (inactive)',
        'variations' => array(
            '0' => 'Facing east (attached to a block to its west)',
            '1' => 'Facing west (attached to a block to its east)',
            '2' => 'Facing south (attached to a block to its north)',
            '3' => 'Facing north (attached to a block to its south)',
            '4' => 'Facing up (attached to a block beneath it)',
        ),
    ),
    'unpowered_comparator' => array(
        'stack' => 64,
        'id' => 149,
        'display_name' => 'Redstone Comparator',
    ),
    'unpowered_repeater' => array(
        'stack' => 64,
        'id' => 93,
        'display_name' => 'Redstone Repeater (inactive)',
    ),
    'vine' => array(
        'stack' => 64,
        'id' => 106,
        'display_name' => 'Vines',
    ),
    'wall_banner' => array(
        'stack' => 16,
        'id' => 177,
        'display_name' => 'Wall Banner',
    ),
    'wall_sign' => array(
        'stack' => 16,
        'id' => 68,
        'display_name' => 'Wall Sign',
    ),
    'water' => array(
        'stack' => 0,
        'id' => 9,
        'display_name' => 'Stationary Water',
    ),
    'water_bucket' => array(
        'stack' => 1,
        'id' => 326,
        'display_name' => 'Water Bucket',
    ),
    'waterlily' => array(
        'stack' => 64,
        'id' => 111,
        'display_name' => 'Lily Pad',
    ),
    'web' => array(
        'stack' => 64,
        'id' => 30,
        'display_name' => 'Cobweb',
    ),
    'wheat' => array(
        'stack' => 64,
        'id' => 296,
        'display_name' => 'Wheat',
    ),
    'wheat_seeds' => array(
        'stack' => 64,
        'id' => 295,
        'display_name' => 'Seeds',
    ),
    'white_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 235,
        'display_name' => 'White Glazed Terracotta',
    ),
    'white_shulker_box' => array(
        'stack' => 1,
        'id' => 219,
        'display_name' => 'White Shulker Box',
    ),
    'wooden_axe' => array(
        'stack' => 1,
        'id' => 271,
        'display_name' => 'Wooden Axe',
    ),
    'wooden_button' => array(
        'stack' => 64,
        'id' => 143,
        'display_name' => 'Wooden Button',
    ),
    'wooden_door' => array(
        'stack' => 64,
        'id' => 324,
        'display_name' => 'Oak Door',
    ),
    'wooden_hoe' => array(
        'stack' => 1,
        'id' => 290,
        'display_name' => 'Wooden Hoe',
    ),
    'wooden_pickaxe' => array(
        'stack' => 1,
        'id' => 270,
        'display_name' => 'Wooden Pickaxe',
    ),
    'wooden_pressure_plate' => array(
        'stack' => 64,
        'id' => 72,
        'display_name' => 'Wooden Pressure Plate',
    ),
    'wooden_shovel' => array(
        'stack' => 1,
        'id' => 269,
        'display_name' => 'Wooden Shovel',
    ),
    'wooden_slab' => array(
        'stack' => 64,
        'id' => 126,
        'display_name' => 'Wooden Slab',
        'variations' => array(
            '0' => 'Oak Wood Slab',
            '1' => 'Spruce Wood Slab',
            '2' => 'Birch Wood Slab',
            '3' => 'Jungle Wood Slab',
            '4' => 'Acacia Wood Slab',
            '5' => 'Dark Oak Wood Slab',
            '8' => 'Upper Oak Wood Slab',
            '9' => 'Upper Spruce Wood Slab',
            '10' => 'Upper Birch Wood Slab',
            '11' => 'Upper Jungle Wood Slab',
            '12' => 'Upper Acacia Wood Slab',
            '13' => 'Upper Dark Oak Wood Slab',
        ),
    ),
    'wooden_sword' => array(
        'stack' => 1,
        'id' => 268,
        'display_name' => 'Wooden Sword',
    ),
    'wool' => array(
        'stack' => 64,
        'id' => 35,
        'display_name' => 'Wool',
    ),
    'writable_book' => array(
        'stack' => 1,
        'id' => 386,
        'display_name' => 'Book and Quill',
    ),
    'written_book' => array(
        'stack' => 16,
        'id' => 387,
        'display_name' => 'Written Book',
    ),
    'yellow_flower' => array(
        'stack' => 64,
        'id' => 37,
        'display_name' => 'Dandelion',
    ),
    'yellow_glazed_terracotta' => array(
        'stack' => 64,
        'id' => 239,
        'display_name' => 'Yellow Glazed Terracotta',
    ),
    'yellow_shulker_box' => array(
        'stack' => 1,
        'id' => 223,
        'display_name' => 'Yellow Shulker Box',
    ),
);