<?php
$PLUGIN_LIST = array(
    '0' => '/home/minecraft/server/bin/websend_inc/donation.inc.php',
    '1' => '/home/minecraft/server/bin/websend_inc/depositbox.inc.php',
    '2' => '/home/minecraft/server/bin/websend_inc/nocheatplus.inc.php',
    '3' => '/home/minecraft/server/bin/websend_inc/hunger.inc.php',
    '4' => '/home/minecraft/server/bin/websend_inc/userlevel.inc.php',
    '5' => '/home/minecraft/server/bin/websend_inc/teamspeak.inc.php',
    '6' => '/home/minecraft/server/bin/websend_inc/mail.inc.php',
    '7' => '/home/minecraft/server/bin/websend_inc/vote.inc.php',
    '8' => '/home/minecraft/server/bin/websend_inc/trivia.inc.php',
    '9' => '/home/minecraft/server/bin/websend_inc/money.inc.php',
    '10' => '/home/minecraft/server/bin/websend_inc/web.inc.php',
    '11' => '/home/minecraft/server/bin/websend_inc/hardcore.inc.php',
    '12' => '/home/minecraft/server/bin/websend_inc/info.inc.php',
    '13' => '/home/minecraft/server/bin/websend_inc/shop.inc.php',
    '14' => '/home/minecraft/server/bin/websend_inc/home.inc.php',
    '15' => '/home/minecraft/server/bin/websend_inc/lottery.inc.php',
    '16' => '/home/minecraft/server/bin/websend_inc/lot.inc.php',
    '17' => '/home/minecraft/server/bin/websend_inc/xp.inc.php',
    '18' => '/home/minecraft/server/bin/websend_inc/contests.inc.php',
    '19' => '/home/minecraft/server/bin/websend_inc/vanity.inc.php',
    '20' => '/home/minecraft/server/bin/websend_inc/skyblock.inc.php',
    '21' => '/home/minecraft/server/bin/websend_inc/story.inc.php',
    '22' => '/home/minecraft/server/bin/websend_inc/mod.inc.php',
    '23' => '/home/minecraft/server/bin/websend_inc/achievements.inc.php',
    '24' => '/home/minecraft/server/bin/websend_inc/karma.inc.php',
);