<?php
global $UMC_POTION_EFFECTS;

$UMC_POTION_EFFECTS = array(
    1 => array('text'=>'Speed', 'code' => 'speed'),
    2 => array('text'=>'Slowness', 'code' => 'slowness'),
    3 => array('text'=>'Haste', 'code' => 'haste'),
    4 => array('text'=>'Mining Fatigue', 'code' => 'mining_fatigue'),
    5 => array('text'=>'Strength', 'code' => 'strength'),
    6 => array('text'=>'Instant Health', 'code' => 'instant_health'),
    7 => array('text'=>'Instant Damage', 'code' => 'instant_damage'),
    8 => array('text'=>'Jump Boost', 'code' => 'jump_boost'),
    9 => array('text'=>'Nausea', 'code' => 'nausea'),
    10 => array('text'=>'Regeneration', 'code' => 'regeneration'),
    11 => array('text'=>'Resistance', 'code' => 'resistance'),
    12 => array('text'=>'Fire Resistance', 'code' => 'fire_resistance'),
    13 => array('text'=>'Water Breathing', 'code' => 'water_breathing'),
    14 => array('text'=>'Invisibility', 'code' => 'invisibility'),
    15 => array('text'=>'Blindness', 'code' => 'blindness'),
    16 => array('text'=>'Night Vision', 'code' => 'night_vision'),
    17 => array('text'=>'Hunger', 'code' => 'hunger'),
    18 => array('text'=>'Weakness', 'code' => 'weakness'),
    19 => array('text'=>'Poison', 'code' => 'poison'),
    20 => array('text'=>'Wither', 'code' => 'wither'),
    21 => array('text'=>'Health Boost', 'code' => 'health_boost'),
    22 => array('text'=>'Absorption', 'code' => 'absorption'),
    23 => array('text'=>'Saturation', 'code' => 'saturation'),
    24 => array('text'=>'Glowing', 'code' => 'glowing'),
    25 => array('text'=>'Levitation', 'code' => 'levitation'),
    26 => array('text'=>'Luck', 'code' => 'luck'),
    27 => array('text'=>'Bad Luck', 'code' => 'unluck'),
);